ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DutchTreat.ViewModels
{
  public class ContactViewModel
  {
    [Required]
    [MinLength(5)]
    public string Name { get; set; }
    [Required]
    [EmailAddress]
    public string Email { get; set; }
    [Required]
    public string Subject { get; set; }
    [Required]
    [MaxLength(250, ErrorMessage = "Too long")]
    public string Message { get; set; }
  }
}

Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DutchTreat.Data;
using DutchTreat.Services;
using DutchTreat.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DutchTreat.Controllers
{
  public class AppController : Controller
  {
    private readonly IMailService _mailService;
    private readonly IDutchRepository _repository;

    public AppController(IMailService mailService, IDutchRepository repository)
    {
      _mailService = mailService;
      _repository = repository;
    }

    public IActionResult Index()
    {
      return View();
    }

    [HttpGet("contact")]
    public IActionResult Contact()
    {
      return View();
    }

    [HttpPost("contact")]
    public IActionResult Contact(ContactViewModel model)
    {
      if (ModelState.IsValid)
      {
        // Send the Email
        _mailService.SendMessage("shawn@wildermuth.com", model.Subject, $"From: {model.Name} - {model.Email}, Message: {model.Message}");
        ViewBag.UserMessage = "Mail Sent...";
        ModelState.Clear();
      }

      return View();
    }

    public IActionResult About()
    {
      return View();
    }

    public IActionResult Shop()
    {
      var results = _repository.GetAllProducts();

      return View(results);
    }
  }
}

Views/App/About.cshtml
<h2>About Us</h2>
<p>More to follow</p>

Views/App/Contact.cshtml
@model ContactViewModel
@{
  ViewBag.Title = "Contact Us";
}
@section Scripts {
  <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
  <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}
<div class="col-md-6 offset-md-3">
  <div class="card card-body bg-light">
    <form method="post">
      
      <div asp-validation-summary="ModelOnly "> </div>

      <div class="form-group">
        <label asp-for="Name">Username:</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
      </div>
      
      <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input type="email" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      
      <div class="form-group">
        <label asp-for="Subject">Subject:</label>
        <input type="text" asp-for="Subject" class="form-control" />
        <span asp-validation-for="Subject" class="text-danger"></span>
      </div>

      <div class="form-group">
        <label asp-for="Message">Message:</label>
        <textarea rows="4" asp-for="Message" class="form-control"></textarea>
        <span asp-validation-for="Message" class="text-danger"></span>
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-primary"><i class='fas fa-envelope'></i> Send Message</button>
        <div class="text-success">@ViewBag.UserMessage</div>
      </div>
    </form>
  </div>
</div>

Views/App/Index.cshtml
@{
  ViewBag.Title = "Home Page";
}
<div class="row">
  <div class="col-md-9">
    <div class="product-info">
      <img src="~/img/VanGogh.jpg" />
      <h3>Mug</h3>
      <ul class="products-props">
        <li>Price: $9.99</li>
        <li>Artist: Van Gogh</li>
        <li>Title: </li>
        <li>Description: Self-Portrait</li>
      </ul>
      <button id="buyButton" class="btn btn-success">Buy</button>
    </div>

    <div id="theForm">
      <form>
        <label>Username:</label>
        <br />
        <input />
        <br />
        <label>Email:</label>
        <br />
        <input type="email" />
        <br />
        <label>Subject:</label>
        <br />
        <input type="text" />
        <br />
        <label>Message:</label>
        <br />
        <textarea rows="4"> </textarea>
        <br />
        <input type="submit" value="Send Message" />
      </form>
    </div>

    <div>
      <div id="loginToggle">Login</div>
      <form class="popup-form">
        <div>
          <label>Username</label>
          <input />
        </div>
        <div>
          <label>Password</label>
          <input type="password" />
        </div>
        <div>
          <input type="checkbox" />
          <label>Remember me?</label>
        </div>
        <div>
          <input type="submit" value="Login" />
        </div>
      </form>
    </div>
  </div>
  <div class="col-md-3">
    <p>This is a fun site to do some buying of Dutch products.</p>
  </div>
</div>

Views/App/Shop.cshtml
@model IEnumerable<Product>
<h1>Shop</h1>
<p>Count: @Model.Count()</p>
<div class="row">
  @foreach (var p in Model)
  {
  <div class="col-md-3">
    <div class="border bg-light rounded p-1">
      <img src="~/img/@(p.ArtId).jpg" class="img-fluid" alt="@p.Artist" />
      <h3>@p.Category - @p.Size</h3>
      <ul class="products-props">
        <li>Price: $@p.Price</li>
        <li>Artist: @p.Artist</li>
        <li>Title: @p.Title </li>
        <li>Description: @p.ArtDescription</li>
      </ul>
      <button id="buyButton" class="btn btn-success">Buy</button>
    </div>
  </div>
  }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <title>Dutch Treat: @ViewBag.Title</title>
  <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
  <div class="row">
    <header class="container-fluid">
      <nav class="navbar navbar-dark bg-dark navbar-expand-md">
        <h1 class="navbar-brand"><i class="fas fa-paint-brush"></i >Dutch Treat</h1>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="theMenu" class="navbar-collapse collapse">
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Index">Home</a></li>
            <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a></li>
            <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="About">About</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <section class="container">
      <h2 class="text-center">@ViewBag.Title</h2>
      @RenderBody()
    </section>
    <footer class="container">
      <div class="text-center">Copyright 2020 Dutch Treat LLC</div>
    </footer>
  </div>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/lib/fortawesome/fontawesome-free/js/fontawesome.js"></script>
  <script src="~/lib/fortawesome/fontawesome-free/js/solid.js"></script>
  <script src="~/js/index.js"></script>
  @RenderSection("scripts", false)
</body>
</html> 